<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpecializationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $specializations = [
            ['name' => 'IT'],
            ['name' => 'Design & Creative'],
            ['name' => 'Sales & Marketing'],
            ['name' => 'Writing & Translation'],
            ['name' => 'Customer Support'],
            ['name' => 'Finance & Accounting'],
            ['name' => 'Legal'],
            ['name' => 'Engineering & Architecture'],
            ['name' => 'Education & Training'],
            ['name' => 'HR & Recruiting'],
            ['name' => 'Administrative & Virtual Assistant'],
            ['name' => 'Healthcare & Medical'],
            ['name' => 'Data Science & Analytics'],
            ['name' => 'Project Management'],
            ['name' => 'Consulting'],
            ['name' => 'Media & Communications'],
            ['name' => 'Art & Illustration'],
            ['name' => 'Research'],
            ['name' => 'Photography & Videography'],
            ['name' => 'Product Management'],
            ['name' => 'Public Relations'],
            ['name' => 'Supply Chain & Logistics'],
            ['name' => 'Operations Management'],
            ['name' => 'Game Development'],
            ['name' => 'Blockchain & Cryptocurrency'],
            ['name' => 'Cybersecurity'],
            ['name' => 'Environmental Science'],
            ['name' => 'Biotechnology'],
            ['name' => 'Robotics'],
            ['name' => 'AI & Machine Learning'],
            ['name' => 'Cloud Computing'],
            ['name' => 'Network Administration'],
            ['name' => 'Mobile App Development'],
            ['name' => 'Web Development'],
            ['name' => 'E-commerce Development'],
            ['name' => 'Content Creation'],
            ['name' => 'Social Media Management'],
            ['name' => 'SEO & SEM'],
            ['name' => 'Advertising'],
            ['name' => 'Branding'],
            ['name' => 'Event Planning'],
            ['name' => 'Fitness & Nutrition'],
            ['name' => 'Life Coaching'],
            ['name' => 'Real Estate'],
            ['name' => 'Insurance'],
            ['name' => 'Transportation'],
            ['name' => 'Manufacturing'],
            ['name' => 'Agriculture'],
            ['name' => 'Energy & Utilities'],
            ['name' => 'Travel & Hospitality'],
            ['name' => 'Retail'],
            ['name' => 'Telecommunications'],
            ['name' => 'Aerospace'],
            ['name' => 'Marine Biology'],
            ['name' => 'Archaeology'],
            ['name' => 'History'],
            ['name' => 'Political Science'],
            ['name' => 'Sociology'],
            ['name' => 'Psychology'],
            ['name' => 'Anthropology'],
            ['name' => 'Philosophy'],
            ['name' => 'Linguistics'],
            ['name' => 'Music'],
            ['name' => 'Theater & Performing Arts'],
            ['name' => 'Fashion Design'],
            ['name' => 'Interior Design'],
            ['name' => 'Automotive'],
            ['name' => 'Food & Beverage'],
            ['name' => 'Journalism'],
            ['name' => 'Broadcasting'],
            ['name' => 'Public Health'],
            ['name' => 'Pharmaceuticals'],
            ['name' => 'Veterinary Science'],
            ['name' => 'Sports & Recreation'],
            ['name' => 'Human Services'],
            ['name' => 'Nonprofit Management'],
            ['name' => 'Urban Planning'],
            ['name' => 'Architecture'],
            ['name' => 'Civil Engineering'],
            ['name' => 'Electrical Engineering'],
            ['name' => 'Mechanical Engineering'],
            ['name' => 'Chemical Engineering'],
            ['name' => 'Materials Science'],
            ['name' => 'Geology'],
            ['name' => 'Meteorology'],
            ['name' => 'Astrophysics'],
            ['name' => 'Quantum Physics'],
            ['name' => 'Nanotechnology'],
            ['name' => 'Ethics'],
            ['name' => 'Religious Studies'],
            ['name' => 'Culinary Arts'],
            ['name' => 'Library Science'],
            ['name' => 'Archival Science'],
            ['name' => 'Oceanography'],
            ['name' => 'Zoology'],
            ['name' => 'Botany'],
            ['name' => 'Genetics'],
            ['name' => 'Neurology'],
            ['name' => 'Oncology'],
            ['name' => 'Pediatrics'],
            ['name' => 'Geriatrics'],
            ['name' => 'Dermatology'],
            ['name' => 'Radiology'],
            ['name' => 'Anesthesiology'],
            ['name' => 'Surgery'],
            ['name' => 'Cardiology'],
            ['name' => 'Psychiatry'],
            ['name' => 'Orthopedics'],
            ['name' => 'Ophthalmology'],
            ['name' => 'Dentistry'],
            ['name' => 'Nutrition Science'],
            ['name' => 'Dietetics'],
            ['name' => 'Physical Therapy'],
            ['name' => 'Occupational Therapy'],
            ['name' => 'Speech-Language Pathology'],
            ['name' => 'Audiology'],
            ['name' => 'Chiropractic'],
            ['name' => 'Acupuncture'],
            ['name' => 'Massage Therapy'],
            ['name' => 'Alternative Medicine'],
            ['name' => 'Holistic Health'],
            ['name' => 'Yoga Instruction'],
            ['name' => 'Pilates Instruction'],
            ['name' => 'Personal Training'],
            ['name' => 'Strength & Conditioning'],
            ['name' => 'Sports Medicine'],
            ['name' => 'Athletic Training'],
            ['name' => 'Kinesiology'],
            ['name' => 'Rehabilitation Science'],
            ['name' => 'Gerontology'],
            ['name' => 'Human Development'],
            ['name' => 'Child Development'],
            ['name' => 'Family Studies'],
            ['name' => 'Gender Studies'],
            ['name' => 'Cultural Studies'],
            ['name' => 'Disability Studies'],
            ['name' => 'Labor Studies'],
            ['name' => 'Peace & Conflict Studies'],
            ['name' => 'Security Studies'],
            ['name' => 'International Relations'],
            ['name' => 'Development Studies'],
            ['name' => 'Global Health'],
            ['name' => 'Public Administration'],
            ['name' => 'Public Policy'],
            ['name' => 'Criminology'],
            ['name' => 'Forensic Science'],
            ['name' => 'Law Enforcement'],
            ['name' => 'Fire Science'],
            ['name' => 'Emergency Management'],
            ['name' => 'Homeland Security'],
            ['name' => 'Corrections'],
            ['name' => 'Probation & Parole'],
            ['name' => 'Judiciary'],
            ['name' => 'Court Administration'],
            ['name' => 'Legal Assistance'],
            ['name' => 'Paralegal Studies'],
            ['name' => 'Taxation'],
            ['name' => 'Estate Planning'],
            ['name' => 'Intellectual Property'],
            ['name' => 'Corporate Law'],
            ['name' => 'Criminal Law'],
            ['name' => 'Civil Law'],
            ['name' => 'Family Law'],
            ['name' => 'Immigration Law'],
            ['name' => 'International Law'],
            ['name' => 'Sports Law'],
            ['name' => 'Entertainment Law'],
            ['name' => 'Real Estate Law'],
            ['name' => 'Labor Law'],
            ['name' => 'Employment Law'],
            ['name' => 'Consumer Law'],
            ['name' => 'Environmental Law'],
            ['name' => 'Health Law'],
            ['name' => 'Education Law'],
            ['name' => 'Human Rights Law'],
            ['name' => 'Animal Law'],
            ['name' => 'Aviation Law'],
            ['name' => 'Space Law']
        ];

        DB::table('specializations')->insert($specializations);
    }
}
